baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Very cool site"

markup.highlight.style = "onedark"

[[menus.main]]
name = 'root'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'blog'
pageRef = '/blog'
weight = 20

[[menus.main]]
name = "dots"
pageRef = "/dots"
weight = 30

[params]
[params.author]
name = "Zenneh"
git = "https://github.com/zenneh"
instagram = "https://instagram.com/senne.wertelaers"

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
